name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build Android App
        run: flutter build apk --split-per-abi
      - name: Rename file
        run: mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/${{ github.event.repository.name }}.apk
      - name: Curl Upload APK
        uses: wei/curl@v1
        with:
          args: --location --request POST  https://gitnotifi.herokuapp.com/uploader --form file=@build/app/outputs/flutter-apk/${{ github.event.repository.name }}.apk
